install.packages("arules")
require(arules)
groceries=read.transactions("data/groceries.csv",sep = ",")
summary(groceries)
str(groceries)
inspect(groceries[1:5])
itemFrequency(groceries[,1:3])
itemFrequencyPlot(groceries,support=0.1)
itemFrequencyPlot(groceries,topN=20)
image(groceries[1:5])
image(sample(groceries,100))
apriori(groceries)
groceriesrule=apriori(groceries,parameter = list(support=0.006,confidence=0.25,minlen=2))
groceriesrule
summary(groceriesrule)
inspect(groceriesrule[1:3])
inspect(sort(groceriesrule,by="lift")[1:5])
berryrules<-subset(groceriesrule,items %in% "berries")
inspect(berryrules)
