#install.packages("RMySQL")
#install.packages("ggplot2")
library(RMySQL)
library(ggplot2)
#install.packages("sqldf")
#library(sqldf)
#sqldf("select * from dc.APP_KAOLA_ITEM",dbname="dc",drv="MySQL",user="dc_read",password="data_center_rd",host="122.11.54.170",port=4300)
conn <- dbConnect(MySQL(), dbname = "dc", username="dc_read", password="data_center_rd", host="122.11.54.170", port=4300)
dbSendQuery(conn,"SET NAMES utf8 ")
item_price <- dbSendQuery(conn, "select cast(price AS UNSIGNED INTEGER) as price,count(distinct product_no) as num from APP_KAOLA_ITEM group by cast(price AS UNSIGNED INTEGER)") 
item_price <- dbFetch(item_price)
#ggplot(item_price, aes(x='price', fill='cut')) +geom_density(alpha=0.25) +facet_wrap("clarity")
plot(item_price$num,item_price$price)
#dbDisconnect(conn)
