#install.packages("RMySQL")
#install.packages("ggplot2")
library(RMySQL)
library(ggplot2)
#install.packages("sqldf")
#library(sqldf)
conn <- dbConnect(MySQL(), dbname = "test", username="root", password="root", host="127.0.0.1", port=3306)
dbSendQuery(conn,"SET NAMES utf8 ")
item_price <- dbSendQuery(conn, "select cast(price AS UNSIGNED INTEGER) as price,count(distinct product_no) as num from APP_KAOLA_ITEM group by cast(price AS UNSIGNED INTEGER)") 
item_price <- dbFetch(item_price)
#ggplot(item_price, aes(x='price', fill='cut')) +geom_density(alpha=0.25) +facet_wrap("clarity")
plot(item_price$num,item_price$price)
#dbDisconnect(conn)
