production=read.table("http://www.stat.tamu.edu/~sheather/book/docs/datasets/production.txt",
                      header = T,sep="")
head(production)
str(production)
plot(RunTime~RunSize,data=production)
production_lm=lm(RunTime~RunSize,data=production)
summary(production_lm)
with(production,plot(RunSize,RunTime))
abline(production_lm)
plot(production_lm)
head(data.frame(production,fitted.value=fitted(production_lm),residual=resid(production_lm)))
anova(production_lm)

changeover=read.table("http://www.stat.tamu.edu/~sheather/book/docs/datasets/changeover_times.txt",
                      header = T,sep="")
head(changeover)
summary(changeover)
changeover$New=factor(changeover$New)
plot(Changeover~New,data = changeover)
changeover_lm=lm(Changeover~New,data = changeover)
summary(changeover_lm)

anscombe=read.table("http://www.stat.tamu.edu/~sheather/book/docs/datasets/anscombe.txt",
                    header = T,sep="")
head(anscombe)
a1_lm=lm(y1~x1,data=anscombe)
a2_lm=lm(y2~x2,data=anscombe)
a3_lm=lm(y3~x3,data=anscombe)
a4_lm=lm(y4~x4,data=anscombe)
par(mfrow=c(2,2))
plot(y1~x1,data=anscombe)
abline(a1_lm,col=2)
plot(y2~x2,data=anscombe)
abline(a2_lm,col=2)
plot(y3~x4,data=anscombe)
abline(a3_lm,col=2)
plot(y4~x4,data=anscombe)
abline(a4_lm,col=2)
plot(resid(a1_lm)~x1,data=anscombe)
plot(resid(a1_lm)~fitted(a1_lm))
plot(resid(a2_lm)~fitted(a2_lm))
plot(resid(a3_lm)~fitted(a3_lm))
plot(resid(a4_lm)~fitted(a4_lm))

cleaning=read.table("http://www.stat.tamu.edu/~sheather/book/docs/datasets/cleaning.txt",
                    header = T,sep="")
par(mfrow=c(2,2))
cleaning_lm=lm(Rooms~Crews,data = cleaning)
plot(Rooms~Crews,data = cleaning)
abline(cleaning_lm,col=2)
plot(cleaning_lm)

#install.packages("DAAG")
library("DAAG")
data(allbacks)
allbacks_lm=lm(weight~volume+area,data = allbacks)
summary(allbacks_lm,corr=TRUE)
par(mfrow=c(2,2))
plot(allbacks_lm)

#install.packages("faraway")
library(faraway)
data(savings)
attach(savings)
head(savings)
savings_lm=lm(sr~pop15+pop75+dpi+ddpi,data=savings)
summary(savings_lm)
savings_lm1=lm(sr~pop75+dpi+ddpi,data=savings)
summary(savings_lm1)
anova(savings_lm,savings_lm1)
